version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get update -y
      - apt-get install maven -y
  pre_build:
    commands:
      - echo nothing to do in prebuild phase...
  build:
    commands:
      - echo build started on `date`
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar