version: 0.2

phases:
  install:
    commands:
      - echo nothing to do in the install phase...
  pre_build:
    commands:
      - echo nothing to do in prebuild phase...
  build:
    commands:
      - echo build started on `date`
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar